### ISSUE TITLE
Stopped working - update on the intra

### ISSUE THREAD

**Issue by huntervcx** [Thezap/Linker_EPITECH_To_GOOGLE_Calendar#13]
Error in room code since yesterday for many people.

`Traceback (most recent call last):
  File "main.py", line 38, in <module>
    main()
  File "main.py", line 33, in main
    calendar_craller.create_event(i, CALENDAR_ID)
  File "/home/huntervcx/Documents/Linker/calendar_craller.py", line 103, in create_event
    "location": event_param['room']['code'],
KeyError: 'code'`

**Comment by Thezap** [comment]
I merge a fix to this, they appende when a activities doesn't have room assigned,
Now i juste create the activities with a empty room this should fix your problem
