### ISSUE TITLE
DAV calendar support

### ISSUE THREAD

**Issue by Thesola10** [Thezap/Linker_EPITECH_To_GOOGLE_Calendar#22]
**Is your feature request related to a problem? Please describe.**
I don't use Google Calendar (unbelievable, I know) but I still want a way to read the EPITECH planner on my calendar, which is hosted on Nextcloud.

**Describe the solution you'd like**
A way to link this program to a WebDAV calendar for event management as an alternative to Google Calendar.

**Additional context**
N/A

**Comment by Thezap** [comment]
I don't know WebDav, but i like to add a support for it.
I doesn't have many time now, but you can make a PR if you want this fast. Otherwise I check to add this when a have more time, maybe in 2 or 3 week.
