### ISSUE TITLE
Linker Broken

### ISSUE THREAD

**Issue by rmaxi-me** [Thezap/Linker_EPITECH_To_GOOGLE_Calendar#6]
The linker recently broke.
It justs doesn't work anymore.

Any ideas how to fix it?

**Comment by Thezap** [comment]
Check your  EPITECH auto-loging link, they been reset by the BOCAL,
I'm going to add a display of error when the auto-loging is invalid or when the intra is down.

**Comment by rmaxi-me** [comment]
Oooh I indeed changed my auto-login link.  
I forgot to change it, sorry for the inconvenience.
